### ISSUE TITLE
Inspire plugin no longer working in QGIS

### ISSUE THREAD

**Issue by StefanGestel** [warrieka/inspireNL#10]
When using the search function in the Inspire plugin, I'm getting this error:

2024-10-07T17:00:01     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

in the python error tab;

2024-10-07T17:04:13     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inspireNL\dataCatalog.py", line 183, in onZoekClicked
              self.search()
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inspireNL\dataCatalog.py", line 220, in search
              searchResult = self.md.searchAll( self.zoek, orgName, dataType, inspiretheme, inspireServiceType)
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inspireNL\metadataParser.py", line 235, in searchAll
              count = int( searchResult.attrib["numberOfRecordsMatched"] )
             AttributeError: 'NoneType' object has no attribute 'attrib'

**Comment by oalbers** [comment]
Found this plugin and had the same error. After searching, It looks like a change in the backend, because in https://github.com/geonetwork/core-geonetwork/pull/5061 they throw an error by default :) So that's why the plugin doesn't get any data :(
